#############################################################################
# Makefile for building: CMS_API_checker
# Generated by qmake (3.1) (Qt 6.2.0)
# Project:  CMS_API_checker.pro
# Template: app
# Command: /opt/Qt/6.2.0/gcc_64/bin/qmake -o Makefile CMS_API_checker.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/opt/Qt/6.2.0/gcc_64/include -I/opt/Qt/6.2.0/gcc_64/include/QtGui -I/opt/Qt/6.2.0/gcc_64/include/QtCore -I. -I/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt/6.2.0/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/Qt/6.2.0/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/Qt/6.2.0/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CMS_API_checker1.0.0
DISTDIR = /home/tnrdll/QT_Projects/CMS_API_checker/.tmp/CMS_API_checker1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/Qt/6.2.0/gcc_64/lib
LIBS          = $(SUBLIBS) /opt/Qt/6.2.0/gcc_64/lib/libQt6Gui.so /opt/Qt/6.2.0/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cmsmanagement.cpp \
		dbmanager.cpp \
		dialog2.cpp \
		main.cpp \
		mainwindow.cpp \
		setupfrombackup.cpp \
		setupfrombackupddev.cpp \
		setupfromgitlab.cpp \
		todo.cpp qrc_cms.cpp \
		moc_cmsmanagement.cpp \
		moc_dialog2.cpp \
		moc_mainwindow.cpp \
		moc_setupfrombackup.cpp \
		moc_setupfrombackupddev.cpp \
		moc_setupfromgitlab.cpp
OBJECTS       = cmsmanagement.o \
		dbmanager.o \
		dialog2.o \
		main.o \
		mainwindow.o \
		setupfrombackup.o \
		setupfrombackupddev.o \
		setupfromgitlab.o \
		todo.o \
		qrc_cms.o \
		moc_cmsmanagement.o \
		moc_dialog2.o \
		moc_mainwindow.o \
		moc_setupfrombackup.o \
		moc_setupfrombackupddev.o \
		moc_setupfromgitlab.o
DIST          = /opt/Qt/6.2.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/toolchain.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/resources_functions.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/lex.prf \
		CMS_API_checker.pro cmsmanagement.h \
		dbmanager.h \
		dialog2.h \
		mainwindow.h \
		setupfrombackup.h \
		setupfrombackupddev.h \
		setupfromgitlab.h cmsmanagement.cpp \
		dbmanager.cpp \
		dialog2.cpp \
		main.cpp \
		mainwindow.cpp \
		setupfrombackup.cpp \
		setupfrombackupddev.cpp \
		setupfromgitlab.cpp \
		todo.cpp
QMAKE_TARGET  = CMS_API_checker
DESTDIR       = 
TARGET        = CMS_API_checker


first: all
####### Build rules

CMS_API_checker:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CMS_API_checker.pro /opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt/6.2.0/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/toolchain.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/resources_functions.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/qmake_use.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/file_copies.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/6.2.0/gcc_64/mkspecs/features/lex.prf \
		CMS_API_checker.pro \
		cms.qrc \
		/opt/Qt/6.2.0/gcc_64/lib/libQt6Gui.prl \
		/opt/Qt/6.2.0/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile CMS_API_checker.pro
/opt/Qt/6.2.0/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/common/unix.conf:
/opt/Qt/6.2.0/gcc_64/mkspecs/common/linux.conf:
/opt/Qt/6.2.0/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt/6.2.0/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt/6.2.0/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt/6.2.0/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt/6.2.0/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt/6.2.0/gcc_64/mkspecs/qconfig.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/toolchain.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/qt.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/resources_functions.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/resources.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/moc.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/qmake_use.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/file_copies.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt/6.2.0/gcc_64/mkspecs/features/lex.prf:
CMS_API_checker.pro:
cms.qrc:
/opt/Qt/6.2.0/gcc_64/lib/libQt6Gui.prl:
/opt/Qt/6.2.0/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CMS_API_checker.pro

qmake_all: FORCE


all: Makefile CMS_API_checker

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents cms.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/Qt/6.2.0/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cmsmanagement.h dbmanager.h dialog2.h mainwindow.h setupfrombackup.h setupfrombackupddev.h setupfromgitlab.h $(DISTDIR)/
	$(COPY_FILE) --parents cmsmanagement.cpp dbmanager.cpp dialog2.cpp main.cpp mainwindow.cpp setupfrombackup.cpp setupfrombackupddev.cpp setupfromgitlab.cpp todo.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_cms.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_cms.cpp
qrc_cms.cpp: cms.qrc \
		/opt/Qt/6.2.0/gcc_64/libexec/rcc \
		style/Combinear.qss \
		style/SyNet.qss \
		style/Adaptic.qss \
		style/Chatbee.qss \
		style/Modern.qss \
		scripts/setup_cms.sh \
		images/fedora.png \
		images/run.png \
		images/drupal.png \
		images/ddev.png \
		images/gitlab.png \
		images/compare.png \
		images/api.png
	/opt/Qt/6.2.0/gcc_64/libexec/rcc -name cms cms.qrc -o qrc_cms.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/Qt/6.2.0/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /opt/Qt/6.2.0/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_cmsmanagement.cpp moc_dialog2.cpp moc_mainwindow.cpp moc_setupfrombackup.cpp moc_setupfrombackupddev.cpp moc_setupfromgitlab.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cmsmanagement.cpp moc_dialog2.cpp moc_mainwindow.cpp moc_setupfrombackup.cpp moc_setupfrombackupddev.cpp moc_setupfromgitlab.cpp
moc_cmsmanagement.cpp: cmsmanagement.h \
		moc_predefs.h \
		/opt/Qt/6.2.0/gcc_64/libexec/moc
	/opt/Qt/6.2.0/gcc_64/libexec/moc $(DEFINES) --include /home/tnrdll/QT_Projects/CMS_API_checker/moc_predefs.h -I/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++ -I/home/tnrdll/QT_Projects/CMS_API_checker -I/home/tnrdll/QT_Projects/CMS_API_checker -I/opt/Qt/6.2.0/gcc_64/include -I/opt/Qt/6.2.0/gcc_64/include/QtGui -I/opt/Qt/6.2.0/gcc_64/include/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include cmsmanagement.h -o moc_cmsmanagement.cpp

moc_dialog2.cpp: dialog2.h \
		moc_predefs.h \
		/opt/Qt/6.2.0/gcc_64/libexec/moc
	/opt/Qt/6.2.0/gcc_64/libexec/moc $(DEFINES) --include /home/tnrdll/QT_Projects/CMS_API_checker/moc_predefs.h -I/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++ -I/home/tnrdll/QT_Projects/CMS_API_checker -I/home/tnrdll/QT_Projects/CMS_API_checker -I/opt/Qt/6.2.0/gcc_64/include -I/opt/Qt/6.2.0/gcc_64/include/QtGui -I/opt/Qt/6.2.0/gcc_64/include/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include dialog2.h -o moc_dialog2.cpp

moc_mainwindow.cpp: mainwindow.h \
		dbmanager.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QString \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		moc_predefs.h \
		/opt/Qt/6.2.0/gcc_64/libexec/moc
	/opt/Qt/6.2.0/gcc_64/libexec/moc $(DEFINES) --include /home/tnrdll/QT_Projects/CMS_API_checker/moc_predefs.h -I/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++ -I/home/tnrdll/QT_Projects/CMS_API_checker -I/home/tnrdll/QT_Projects/CMS_API_checker -I/opt/Qt/6.2.0/gcc_64/include -I/opt/Qt/6.2.0/gcc_64/include/QtGui -I/opt/Qt/6.2.0/gcc_64/include/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_setupfrombackup.cpp: setupfrombackup.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QProcess \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h \
		moc_predefs.h \
		/opt/Qt/6.2.0/gcc_64/libexec/moc
	/opt/Qt/6.2.0/gcc_64/libexec/moc $(DEFINES) --include /home/tnrdll/QT_Projects/CMS_API_checker/moc_predefs.h -I/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++ -I/home/tnrdll/QT_Projects/CMS_API_checker -I/home/tnrdll/QT_Projects/CMS_API_checker -I/opt/Qt/6.2.0/gcc_64/include -I/opt/Qt/6.2.0/gcc_64/include/QtGui -I/opt/Qt/6.2.0/gcc_64/include/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include setupfrombackup.h -o moc_setupfrombackup.cpp

moc_setupfrombackupddev.cpp: setupfrombackupddev.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QProcess \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h \
		moc_predefs.h \
		/opt/Qt/6.2.0/gcc_64/libexec/moc
	/opt/Qt/6.2.0/gcc_64/libexec/moc $(DEFINES) --include /home/tnrdll/QT_Projects/CMS_API_checker/moc_predefs.h -I/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++ -I/home/tnrdll/QT_Projects/CMS_API_checker -I/home/tnrdll/QT_Projects/CMS_API_checker -I/opt/Qt/6.2.0/gcc_64/include -I/opt/Qt/6.2.0/gcc_64/include/QtGui -I/opt/Qt/6.2.0/gcc_64/include/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include setupfrombackupddev.h -o moc_setupfrombackupddev.cpp

moc_setupfromgitlab.cpp: setupfromgitlab.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QProcess \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h \
		moc_predefs.h \
		/opt/Qt/6.2.0/gcc_64/libexec/moc
	/opt/Qt/6.2.0/gcc_64/libexec/moc $(DEFINES) --include /home/tnrdll/QT_Projects/CMS_API_checker/moc_predefs.h -I/opt/Qt/6.2.0/gcc_64/mkspecs/linux-g++ -I/home/tnrdll/QT_Projects/CMS_API_checker -I/home/tnrdll/QT_Projects/CMS_API_checker -I/opt/Qt/6.2.0/gcc_64/include -I/opt/Qt/6.2.0/gcc_64/include/QtGui -I/opt/Qt/6.2.0/gcc_64/include/QtCore -I/usr/include/c++/10 -I/usr/include/c++/10/x86_64-redhat-linux -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-redhat-linux/10/include -I/usr/local/include -I/usr/include setupfromgitlab.h -o moc_setupfromgitlab.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

cmsmanagement.o: cmsmanagement.cpp cmsmanagement.h \
		dialog2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmsmanagement.o cmsmanagement.cpp

dbmanager.o: dbmanager.cpp dbmanager.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QString \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QDebug \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringconverter.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qset.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QSortFilterProxyModel \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qabstractproxymodel.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qabstractitemmodel.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qregularexpression.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbmanager.o dbmanager.cpp

dialog2.o: dialog2.cpp dialog2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog2.o dialog2.cpp

main.o: main.cpp mainwindow.h \
		dbmanager.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QString \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QFile \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		dbmanager.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QString \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		setupfrombackup.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QProcess \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h \
		setupfromgitlab.h \
		setupfrombackupddev.h \
		cmsmanagement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

setupfrombackup.o: setupfrombackup.cpp setupfrombackup.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QProcess \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QFile \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QFileInfo \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatetime.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcalendar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringconverter.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qset.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setupfrombackup.o setupfrombackup.cpp

setupfrombackupddev.o: setupfrombackupddev.cpp setupfrombackupddev.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QProcess \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QFile \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qfile.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QFileInfo \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatetime.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcalendar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhash.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringconverter.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qset.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setupfrombackupddev.o setupfrombackupddev.cpp

setupfromgitlab.o: setupfromgitlab.cpp setupfromgitlab.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/QProcess \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtcore-config.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qflags.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qversiontagging.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiodevicebase.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtmetamacros.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstring.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qchar.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpair.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydatapointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qarraydataops.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainertools_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearrayview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringliteral.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qanystringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qutf8stringview.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringtokenizer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qhashfunctions.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcompare.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qscopeguard.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qiterable.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmetacontainer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qcontainerinfo.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qtaggedpointer.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qmath.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qproperty.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt/6.2.0/gcc_64/include/QtCore/qpropertyprivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setupfromgitlab.o setupfromgitlab.cpp

todo.o: todo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o todo.o todo.cpp

qrc_cms.o: qrc_cms.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_cms.o qrc_cms.cpp

moc_cmsmanagement.o: moc_cmsmanagement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmsmanagement.o moc_cmsmanagement.cpp

moc_dialog2.o: moc_dialog2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog2.o moc_dialog2.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_setupfrombackup.o: moc_setupfrombackup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setupfrombackup.o moc_setupfrombackup.cpp

moc_setupfrombackupddev.o: moc_setupfrombackupddev.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setupfrombackupddev.o moc_setupfrombackupddev.cpp

moc_setupfromgitlab.o: moc_setupfromgitlab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setupfromgitlab.o moc_setupfromgitlab.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

